# Generated by Django 5.2.1 on 2025-06-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sliders', '0002_alter_sliderimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderimage',
            name='image',
            field=models.ImageField(upload_to='sliders/'),
        ),
    ]
