# Generated by Django 5.2.1 on 2025-07-14 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_type',
            field=models.CharField(choices=[('physical', 'فیزیکی'), ('digital', 'دیجیتال'), ('both', 'هر دو نسخه')], default='physical', max_length=10),
        ),
        migrations.AddField(
            model_name='book',
            name='digital_file_link',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='لینک فایل دیجیتال'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
