# Generated by Django 5.2.1 on 2025-07-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_book_type_book_digital_file_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='level',
            field=models.CharField(blank=True, choices=[('beginner', 'مبتدی'), ('intermediate', 'متوسط'), ('advanced', 'پیشرفته')], max_length=20, null=True, verbose_name='سطح کتاب'),
        ),
    ]
