# Generated by Django 5.2.1 on 2025-05-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_rename_stock_book_inventory_book_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
