# Generated by Django 5.2.1 on 2025-07-02 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='image',
            new_name='image_url',
        ),
    ]
