# Generated by Django 5.2.1 on 2025-08-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_category_options_category_description_and_more'),
        ('carts', '0002_alter_cart_user_alter_cartitem_book_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('cart', 'book'), name='unique_cart_book'),
        ),
    ]
