# Generated by Django 5.2.1 on 2025-07-30 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
