# Generated by Django 5.2.1 on 2025-08-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_authority',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='کد رهگیری درگاه'),
        ),
    ]
